### ISSUE TITLE
Error 400 Bad request on sending a transfer

### ISSUE THREAD

**Issue by XaviP** [komunitin/komunitin#156]
User: noether
Post: https://demo.integralces.net/ces/api/accounting/NET2/transfers

Body:

> {'data': {'id': 'b0ac5479-afe9-439b-9446-196586559291', 'type': 'transfers', 'attributes': {'amount': 400, 'meta': 'Astrological tips', 'state': 'committed'}, 'relationships': {'payer': {'data': {'type': 'accounts', 'id': '0c1d2b8c-cef9-4120-8675-e19d1a14c636'}}, 'payee': {'data': {'type': 'accounts', 'id': '33d55ab3-1909-4464-9019-a5f7a344fc4f'}}}}}

Error:

> {"errors":[{"status":"400","code":"1006","title":"Bad Request"}]}

**Comment by estevebadia** [comment]
Probably the transfer fails because the JSON is encoded with single quotes instead of double quotes. I've tried and it works properly:

![image](https://user-images.githubusercontent.com/11861370/112728857-90c20e80-8f29-11eb-83e2-57b85e387bef.png)
![image](https://user-images.githubusercontent.com/11861370/112728876-a59ea200-8f29-11eb-9786-a0515a7c2f29.png)
